"use client";

import { useState, useMemo } from "react";

export type Student = {
	id: string; // e.g. "STU20260001" — generated by backend
	first_name: string;
	last_name: string;
	email: string;
	status: "Active" | "Suspended" | "Graduated";
};

const statusStyles: Record<Student["status"], string> = {
	Active: "bg-secondary-container text-on-secondary-container",
	Suspended: "bg-tertiary-container text-on-tertiary-container",
	Graduated: "bg-surface-container-highest text-on-surface-variant",
};

type SortKey = "id" | "first_name" | "last_name" | "email" | "status" | null;
type SortDir = "asc" | "desc";

// Derive a sortable value from any sort key
const sortVal = (s: Student, key: NonNullable<SortKey>) => {
	if (key === "first_name") return s.first_name.toLowerCase();
	if (key === "last_name") return s.last_name.toLowerCase();
	return String(s[key]).toLowerCase();
};

// ── Add Modal ────────────────────────────────────────────────────────────────

type AddForm = {
	first_name: string;
	last_name: string;
	email: string;
	status: Student["status"];
};

function AddStudentModal({
	onSave,
	onClose,
}: {
	onSave: (data: AddForm) => void;
	onClose: () => void;
}) {
	const [form, setForm] = useState<AddForm>({
		first_name: "",
		last_name: "",
		email: "",
		status: "Active",
	});

	const set =
		(k: keyof AddForm) =>
		(e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) =>
			setForm((prev) => ({ ...prev, [k]: e.target.value }));

	return (
		<div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/30 backdrop-blur-sm">
			<div className="bg-white rounded-2xl shadow-2xl w-full max-w-md">
				<div className="flex items-center justify-between px-8 py-6 border-b border-slate-100">
					<h2 className="font-headline font-bold text-xl text-indigo-900">
						Add Student
					</h2>
					<button
						onClick={onClose}
						className="p-2 text-slate-400 hover:text-slate-600 rounded-full transition-colors"
					>
						<span className="material-symbols-outlined">close</span>
					</button>
				</div>

				<form
					onSubmit={(e) => {
						e.preventDefault();
						onSave(form);
					}}
					className="px-8 py-6 space-y-5"
				>
					{/* ID notice */}
					<div className="flex items-center gap-2 px-3 py-2.5 rounded-lg bg-indigo-50 text-indigo-700 text-xs font-medium">
						<span className="material-symbols-outlined text-[16px]">
							info
						</span>
						Student ID will be auto-generated (e.g. STU20260001)
					</div>

					<div className="grid grid-cols-2 gap-4">
						<div className="space-y-1.5">
							<label className="block text-[11px] font-bold uppercase tracking-wider text-slate-500">
								First Name
							</label>
							<input
								value={form.first_name}
								onChange={set("first_name")}
								placeholder="Elena"
								required
								className="w-full px-4 py-2.5 rounded-lg bg-slate-50 border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30"
							/>
						</div>
						<div className="space-y-1.5">
							<label className="block text-[11px] font-bold uppercase tracking-wider text-slate-500">
								Last Name
							</label>
							<input
								value={form.last_name}
								onChange={set("last_name")}
								placeholder="Rodriguez"
								required
								className="w-full px-4 py-2.5 rounded-lg bg-slate-50 border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30"
							/>
						</div>
					</div>

					<div className="space-y-1.5">
						<label className="block text-[11px] font-bold uppercase tracking-wider text-slate-500">
							Email
						</label>
						<input
							type="email"
							value={form.email}
							onChange={set("email")}
							placeholder="elena.r@editorial.edu"
							required
							className="w-full px-4 py-2.5 rounded-lg bg-slate-50 border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30"
						/>
					</div>

					<div className="space-y-1.5">
						<label className="block text-[11px] font-bold uppercase tracking-wider text-slate-500">
							Status
						</label>
						<select
							value={form.status}
							onChange={set("status")}
							className="w-full px-4 py-2.5 rounded-lg bg-slate-50 border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30"
						>
							<option>Active</option>
							<option>Suspended</option>
							<option>Graduated</option>
						</select>
					</div>

					<div className="flex gap-3 pt-2">
						<button
							type="button"
							onClick={onClose}
							className="flex-1 py-2.5 rounded-lg border border-slate-200 text-sm font-semibold text-slate-600 hover:bg-slate-50 transition-colors"
						>
							Cancel
						</button>
						<button
							type="submit"
							className="flex-1 py-2.5 rounded-lg bg-primary text-white text-sm font-semibold hover:bg-primary/90 transition-colors shadow-sm shadow-primary/20"
						>
							Add Student
						</button>
					</div>
				</form>
			</div>
		</div>
	);
}

// ── Edit Modal ───────────────────────────────────────────────────────────────

type EditForm = {
	first_name: string;
	last_name: string;
	email: string;
	status: Student["status"];
	newPassword: string;
};

function EditStudentModal({
	student,
	onSave,
	onClose,
}: {
	student: Student;
	onSave: (data: EditForm) => void;
	onClose: () => void;
}) {
	const [form, setForm] = useState<EditForm>({
		first_name: student.first_name,
		last_name: student.last_name,
		email: student.email,
		status: student.status,
		newPassword: "",
	});

	const set =
		(k: keyof EditForm) =>
		(e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) =>
			setForm((prev) => ({ ...prev, [k]: e.target.value }));

	const resetPassword = () =>
		setForm((prev) => ({ ...prev, newPassword: student.id }));

	return (
		<div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/30 backdrop-blur-sm">
			<div className="bg-white rounded-2xl shadow-2xl w-full max-w-md max-h-[90vh] overflow-y-auto">
				<div className="flex items-center justify-between px-8 py-6 border-b border-slate-100 sticky top-0 bg-white z-10">
					<div>
						<h2 className="font-headline font-bold text-xl text-indigo-900">
							Edit Student
						</h2>
						<p className="text-xs text-slate-400 font-mono mt-0.5">
							{student.id}
						</p>
					</div>
					<button
						onClick={onClose}
						className="p-2 text-slate-400 hover:text-slate-600 rounded-full transition-colors"
					>
						<span className="material-symbols-outlined">close</span>
					</button>
				</div>

				<form
					onSubmit={(e) => {
						e.preventDefault();
						onSave(form);
					}}
					className="px-8 py-6 space-y-5"
				>
					<div className="grid grid-cols-2 gap-4">
						<div className="space-y-1.5">
							<label className="block text-[11px] font-bold uppercase tracking-wider text-slate-500">
								First Name
							</label>
							<input
								value={form.first_name}
								onChange={set("first_name")}
								required
								className="w-full px-4 py-2.5 rounded-lg bg-slate-50 border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30"
							/>
						</div>
						<div className="space-y-1.5">
							<label className="block text-[11px] font-bold uppercase tracking-wider text-slate-500">
								Last Name
							</label>
							<input
								value={form.last_name}
								onChange={set("last_name")}
								required
								className="w-full px-4 py-2.5 rounded-lg bg-slate-50 border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30"
							/>
						</div>
					</div>

					<div className="space-y-1.5">
						<label className="block text-[11px] font-bold uppercase tracking-wider text-slate-500">
							Email
						</label>
						<input
							type="email"
							value={form.email}
							onChange={set("email")}
							required
							className="w-full px-4 py-2.5 rounded-lg bg-slate-50 border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30"
						/>
					</div>

					<div className="space-y-1.5">
						<label className="block text-[11px] font-bold uppercase tracking-wider text-slate-500">
							Status
						</label>
						<select
							value={form.status}
							onChange={set("status")}
							className="w-full px-4 py-2.5 rounded-lg bg-slate-50 border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30"
						>
							<option>Active</option>
							<option>Suspended</option>
							<option>Graduated</option>
						</select>
					</div>

					{/* Password section */}
					<div className="pt-2 border-t border-slate-100 space-y-3">
						<p className="text-[11px] font-bold uppercase tracking-wider text-slate-500">
							Password
						</p>
						<div className="space-y-1.5">
							<div className="flex items-center justify-between">
								<label className="text-xs text-slate-500">
									New password
								</label>
								<button
									type="button"
									onClick={resetPassword}
									className="flex items-center gap-1 text-[11px] font-bold text-indigo-600 hover:text-indigo-800 transition-colors"
								>
									<span className="material-symbols-outlined text-[14px]">
										restart_alt
									</span>
									Reset to Student ID
								</button>
							</div>
							<input
								type="text"
								value={form.newPassword}
								onChange={set("newPassword")}
								placeholder="Leave blank to keep current password"
								className="w-full px-4 py-2.5 rounded-lg bg-slate-50 border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30 font-mono"
							/>
							{form.newPassword === student.id && (
								<p className="text-[11px] text-amber-600 flex items-center gap-1">
									<span className="material-symbols-outlined text-[13px]">
										warning
									</span>
									Password will be reset to student ID
									(default)
								</p>
							)}
						</div>
					</div>

					<div className="flex gap-3 pt-2">
						<button
							type="button"
							onClick={onClose}
							className="flex-1 py-2.5 rounded-lg border border-slate-200 text-sm font-semibold text-slate-600 hover:bg-slate-50 transition-colors"
						>
							Cancel
						</button>
						<button
							type="submit"
							className="flex-1 py-2.5 rounded-lg bg-primary text-white text-sm font-semibold hover:bg-primary/90 transition-colors shadow-sm shadow-primary/20"
						>
							Save Changes
						</button>
					</div>
				</form>
			</div>
		</div>
	);
}

// ── Table ────────────────────────────────────────────────────────────────────

type ModalState =
	| { mode: "closed" }
	| { mode: "add" }
	| { mode: "edit"; student: Student };

export default function StudentTable({
	students: initial,
}: {
	students: Student[];
}) {
	const [students, setStudents] = useState(initial);
	const [search, setSearch] = useState("");
	const [sortKey, setSortKey] = useState<SortKey>(null);
	const [sortDir, setSortDir] = useState<SortDir>("asc");
	const [modal, setModal] = useState<ModalState>({ mode: "closed" });

	const filtered = useMemo(() => {
		let list = students;
		if (search) {
			const q = search.toLowerCase();
			list = list.filter(
				(s) =>
					s.first_name.toLowerCase().includes(q) ||
					s.last_name.toLowerCase().includes(q) ||
					s.email.toLowerCase().includes(q) ||
					s.id.toLowerCase().includes(q),
			);
		}
		if (sortKey) {
			list = [...list].sort((a, b) => {
				const av = sortVal(a, sortKey);
				const bv = sortVal(b, sortKey);
				return sortDir === "asc"
					? av.localeCompare(bv)
					: bv.localeCompare(av);
			});
		}
		return list;
	}, [students, search, sortKey, sortDir]);

	const toggleSort = (key: SortKey) => {
		if (!key) return;
		if (sortKey === key) setSortDir((d) => (d === "asc" ? "desc" : "asc"));
		else {
			setSortKey(key);
			setSortDir("asc");
		}
	};

	const handleAdd = (data: AddForm) => {
		// TODO: POST /students — backend generates real ID
		const mockId = `STU${new Date().getFullYear()}${String(Date.now()).slice(-4)}`;
		setStudents((prev) => [...prev, { ...data, id: mockId }]);
		setModal({ mode: "closed" });
	};

	const handleEdit = (data: EditForm) => {
		// TODO: PATCH /students/:id — send data + newPassword if set
		if (modal.mode !== "edit") return;
		const updated: Student = {
			...modal.student,
			first_name: data.first_name,
			last_name: data.last_name,
			email: data.email,
			status: data.status,
		};
		setStudents((prev) =>
			prev.map((s) => (s.id === updated.id ? updated : s)),
		);
		setModal({ mode: "closed" });
	};

	const SortIcon = ({ col }: { col: SortKey }) =>
		sortKey === col ? (
			<span className="material-symbols-outlined text-[13px] ml-0.5 text-primary align-middle">
				{sortDir === "asc" ? "arrow_upward" : "arrow_downward"}
			</span>
		) : (
			<span className="material-symbols-outlined text-[13px] ml-0.5 text-slate-300 align-middle">
				unfold_more
			</span>
		);

	const columns: { label: string; key: SortKey }[] = [
		{ label: "ID", key: "id" },
		{ label: "Full Name", key: "last_name" },
		{ label: "Email", key: "email" },
		{ label: "Status", key: "status" },
		{ label: "Actions", key: null },
	];

	return (
		<>
			{modal.mode === "add" && (
				<AddStudentModal
					onSave={handleAdd}
					onClose={() => setModal({ mode: "closed" })}
				/>
			)}
			{modal.mode === "edit" && (
				<EditStudentModal
					student={modal.student}
					onSave={handleEdit}
					onClose={() => setModal({ mode: "closed" })}
				/>
			)}

			<div className="bg-surface-container-lowest rounded-xl overflow-hidden shadow-sm ring-1 ring-slate-200/50">
				{/* Toolbar */}
				<div className="px-8 py-5 flex items-center gap-4 bg-white border-b border-slate-50">
					<h3 className="font-headline font-bold text-indigo-900 shrink-0">
						Current Enrollment
					</h3>
					<div className="relative flex-1 max-w-xs ml-auto">
						<span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 text-[18px]">
							search
						</span>
						<input
							value={search}
							onChange={(e) => setSearch(e.target.value)}
							placeholder="Search students…"
							className="w-full pl-9 pr-4 py-2 text-sm rounded-lg bg-slate-50 border border-slate-200 focus:outline-none focus:ring-2 focus:ring-primary/30"
						/>
					</div>
					<button
						onClick={() => setModal({ mode: "add" })}
						className="flex items-center gap-2 px-4 py-2 bg-primary text-white rounded-lg font-bold text-sm shadow shadow-primary/20 press-effect transition-transform shrink-0"
					>
						<span className="material-symbols-outlined text-[18px]">
							person_add
						</span>
						<span>Add Student</span>
					</button>
				</div>

				<table className="w-full text-left border-collapse">
					<thead>
						<tr className="bg-slate-50/50">
							{columns.map(({ label, key }) => (
								<th
									key={label}
									onClick={() => toggleSort(key)}
									className={`px-8 py-4 text-[11px] uppercase tracking-widest font-bold text-slate-500 ${label === "Actions" ? "text-right" : ""} ${key ? "cursor-pointer hover:text-indigo-700 select-none" : ""}`}
								>
									{label}
									{key && <SortIcon col={key} />}
								</th>
							))}
						</tr>
					</thead>
					<tbody className="divide-y divide-slate-100">
						{filtered.length === 0 ? (
							<tr>
								<td
									colSpan={5}
									className="px-8 py-12 text-center text-slate-400 text-sm"
								>
									No students match your search.
								</td>
							</tr>
						) : (
							filtered.map((student) => (
								<tr
									key={student.id}
									className="group hover:bg-slate-50/80 transition-colors"
								>
									<td className="px-8 py-5 font-mono text-xs text-slate-600 font-medium">
										{student.id}
									</td>
									<td className="px-8 py-5 font-label font-semibold text-slate-900">
										{student.first_name} {student.last_name}
									</td>
									<td className="px-8 py-5 text-sm text-slate-600">
										{student.email}
									</td>
									<td className="px-8 py-5">
										<span
											className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider ${statusStyles[student.status]}`}
										>
											{student.status}
										</span>
									</td>
									<td className="px-8 py-5 text-right">
										<div className="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
											<button
												onClick={() =>
													setModal({
														mode: "edit",
														student,
													})
												}
												className="p-2 text-primary hover:bg-primary/5 rounded-lg transition-colors"
												title="Edit student"
											>
												<span className="material-symbols-outlined text-lg">
													edit_square
												</span>
											</button>
										</div>
									</td>
								</tr>
							))
						)}
					</tbody>
				</table>

				{/* Pagination */}
				<div className="px-8 py-4 bg-slate-50/30 border-t border-slate-100 flex items-center justify-between">
					<p className="text-xs text-slate-500 font-medium">
						Showing {filtered.length} of {students.length} students
					</p>
					<div className="flex items-center gap-2">
						<button
							disabled
							className="p-2 text-slate-400 hover:text-indigo-600 disabled:opacity-30"
						>
							<span className="material-symbols-outlined">
								chevron_left
							</span>
						</button>
						<button className="p-2 text-slate-400 hover:text-indigo-600">
							<span className="material-symbols-outlined">
								chevron_right
							</span>
						</button>
					</div>
				</div>
			</div>
		</>
	);
}
